#!/bin/bash

ones=0
twos=0
threes=0
fours=0
fives=0
sixes=0

for (( i=1; i < 701; i++ ))
do
number=$[1 + RANDOM % 6]
case $number in
1 ) ((ones++));;
2 ) ((twos++));;
3 ) ((threes++));;
4 ) ((fours++));;
5 ) ((fives++));;
6 ) ((sixes++));;
esac
done

echo ones = $ones
echo twos = $twos
echo threes = $threes
echo fours = $fours
echo fives = $fives
echo sixes = $sixes
